apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jukebox-e2e-pipeline
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
  tasks:
    - name: run-e2e-tests
      taskRef:
        name: jukebox-e2e-test
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)