// client/src/utils/countryNames.ts
export const countryNames: Record<string, string> = {
  "AE": "United Arab Emirates",
  "AR": "Argentina",
  "AT": "Austria",
  "AU": "Australia",
  "BE": "Belgium",
  "BG": "Bulgaria",
  "BO": "Bolivia",
  "BR": "Brazil",
  "BY": "Belarus",
  "CA": "Canada",
  "CH": "Switzerland",
  "CL": "Chile",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CZ": "Czech Republic",
  "DE": "Germany",
  "DK": "Denmark",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "ES": "Spain",
  "FI": "Finland",
  "FR": "France",
  "GB": "United Kingdom",
  "GR": "Greece",
  "GT": "Guatemala",
  "HK": "Hong Kong",
  "HN": "Honduras",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IN": "India",
  "IS": "Iceland",
  "IT": "Italy",
  "JP": "Japan",
  "KR": "South Korea",
  "KZ": "Kazakhstan",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "MA": "Morocco",
  "MX": "Mexico",
  "MY": "Malaysia",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NZ": "New Zealand",
  "PA": "Panama",
  "PE": "Peru",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PT": "Portugal",
  "PY": "Paraguay",
  "RO": "Romania",
  "SA": "Saudi Arabia",
  "SE": "Sweden",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SV": "El Salvador",
  "TH": "Thailand",
  "TR": "Turkey",
  "TW": "Taiwan",
  "UA": "Ukraine",
  "US": "United States",
  "UY": "Uruguay",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "ZA": "South Africa"
}